# [START runtime]
runtime: nodejs10
# [END runtime]

# [START handlers]
handlers:
- url: /[a-z]*
  secure: always
  static_files: build/index.html
  upload: build/index.html

- url: /
  secure: always
  static_dir: build
# [END handlers]
